
spring:
  resources:
    static-locations: file:${filePath},classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/testjpa
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
server:
  port: 12345

filePath: D:/fileUpload/
